<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Spaces</AssemblyName>
    <RootNamespace>SpacesBrowser</RootNamespace>
    <Version>1.3.0</Version>
    <UpdateRepository>Antik185/emulator</UpdateRepository>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="UpdateRepository" Value="$(UpdateRepository)" />
  </ItemGroup>
</Project>
